IAU WGSN Star Name Update (2026-04-19) and unofficial names (#322)
New IAU WGSN names:
- Tepiamenit = Tau Boötis -- traditional star name?
- Qigong = Delta Boötis -- WGSN contrived: traditional constellation
- Kalasungsang = Rho Boötis -- WGSN contrived: traditional constellation
"Kala Sungsang", contracted to one word
- Genghe = Sigma Boötis -- WGSN contrived: traditional constellation
- Alrumh = 34 Boötis -- WGSN contrived: traditional constellation
- Maenalus = 109 Virginis -- WGSN contrived: defunct early modern
constellation
- Stella Ludoviciana = HD 116798 -- modern star name

Non-IAU WGSN names:
- Cleeia = Delta3 Tauri -- traditional star name, attached to Delta3
Tauri in recent times. See: https://ase.exopla.net/index.php/Kleeia.
- Speedy Mic = BO Microscopii -- assigned to the star by Bromage et al.
(1992) (https://ui.adsabs.harvard.edu/abs/1992ASPC...26...80B/abstract)
- Toronto Star = HD 199579 -- assigned to the star by Maíz Apellániz et
al. (2022)
(https://www.aanda.org/articles/aa/full_html/2022/01/aa42366-21/aa42366-21.html)
- Zvrk = TIC 350842552 -- assigned to the star by Ong et al. (2024)
(https://iopscience.iop.org/article/10.3847/1538-4357/ad2ea2)
- Papayu = KIC 11029516 -- assigned to the star by Bhalotia et al.
(2024) (https://iopscience.iop.org/article/10.3847/1538-4357/ad4eb1)

Notes
- Tepiamenit = Tau Boötis is an exoplanet host, and as such is in the
Exoplanet Catalog. This update will not cause the name "Tepiamenit" to
appear when selecting the barycentre nor the primary star. Typing the
name will still select TAU Boo barycentre, however.
- Pulcherrima = Epsilon Boötis already exists, alongside Izar and Mirak.
However, this will change in the future. The IAU WGSN has a policy of
assigning names to individual stars, and "Pulcherrima" itself is
assigned to Epsilon Boötis B (and Izar to component A). Celestia has, so
far, followed the "follow the intention of the namer" policy, where
traditional star names are applied to the entire system while WGSN
contrived names follow the WGSN's rules and is applied only to the
primary star. Cases where the system has two or more named stars are the
exception: the names are given to the stars that WGSN assigned.
Effectively, this means when the binarity of Epsilon Boötis is added to
Celestia, the name "Izar" and "Pulcherrima" will be moved to Epsilon
Boötis A and B respectively, and the barycentre will no longer have a
proper name.
- Holoea = IRAS 05327+3404, Bajamar Star = 2MASS J20555125+4352246,
Sapaki = WR 67-1, and Paloma = 2MASS J05243042+4244506 are not in
Celestia currently, and hence are not named in this update.
- Calvera = PSR J1412+7922 already exists.
- "Speedy Mic", "Toronto Star", and "Zvrk" are attested in subsequent
papers. I have not been able to find a subsequent paper that uses
"Papayu".